version: '3'
services:
  shinobi:
    build:
      context: .
      args:
        SHINOBI_BRANCH: master
    volumes:
      - $HOME/buildrootFiles:/home/buildrootFiles
    ports:
      - "18444:8080"
    environment:
    restart: unless-stopped
